CREATE OR REPLACE DATABASE SNOWTRACE_DB;
USE DATABASE SNOWTRACE_DB;

CREATE OR REPLACE WAREHOUSE SNOWTRACE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE SNOWTRACE_WH;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

USE SCHEMA RAW;

CREATE OR REPLACE TABLE RETAIL_TRANSACTIONS (
    TRANSACTION_ID VARCHAR(20) NOT NULL,
    TRANSACTION_DATE DATE,
    DIVISION VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    PRODUCT_NAME VARCHAR(100),
    REVENUE NUMBER(12,2),
    QUANTITY NUMBER(8,0),
    IS_RETURN BOOLEAN,
    IS_PROMO BOOLEAN,
    CHANNEL VARCHAR(20),
    CUSTOMER_SEGMENT VARCHAR(20)
);

INSERT INTO RETAIL_TRANSACTIONS VALUES
('TXN001', '2024-12-05', 'Beauty', 'Fragrances', 'Maison Oud Perfume', 98000, 14, FALSE, FALSE, 'ONLINE', 'PREMIUM'),
('TXN002', '2024-12-11', 'Beauty', 'Fragrances', 'Luxury Amber Set', 87000, 12, FALSE, TRUE, 'IN STORE', 'PREMIUM'),
('TXN003', '2024-12-18', 'Beauty', 'Fragrances', 'Velvet Rose Elixir', 91000, 13, FALSE, FALSE, 'APP', 'PREMIUM'),
('TXN101', '2025-01-05', 'Beauty', 'Fragrances', 'Daily Mist Collection', 28000, 22, FALSE, TRUE, 'ONLINE', 'STANDARD'),
('TXN102', '2025-01-09', 'Beauty', 'Fragrances', 'Travel Fragrance Kit', 24000, 25, FALSE, FALSE, 'APP', 'BUDGET'),
('TXN201', '2024-12-07', 'Fashion', 'Designer Wear', 'Cashmere Evening Coat', 120000, 8, FALSE, FALSE, 'IN STORE', 'PREMIUM'),
('TXN202', '2024-12-19', 'Fashion', 'Designer Wear', 'Luxury Silk Dress', 108000, 9, FALSE, TRUE, 'ONLINE', 'PREMIUM'),
('TXN301', '2025-01-06', 'Fashion', 'Designer Wear', 'Luxury Silk Dress', 101000, 8, FALSE, FALSE, 'ONLINE', 'PREMIUM'),
('TXN302', '2025-01-12', 'Fashion', 'Designer Wear', 'Signature Wool Blazer', 97000, 9, FALSE, FALSE, 'IN STORE', 'STANDARD'),
('TXN401', '2024-12-15', 'Fashion', 'Luxury Handbags', 'Leather Signature Tote', 145000, 6, FALSE, FALSE, 'ONLINE', 'PREMIUM'),
('TXN402', '2025-01-14', 'Fashion', 'Luxury Handbags', 'Leather Signature Tote', 142000, 6, FALSE, FALSE, 'ONLINE', 'PREMIUM'),
('TXN501', '2024-12-10', 'Beauty', 'Skincare', 'Gold Renewal Cream', 42000, 18, FALSE, TRUE, 'APP', 'STANDARD'),
('TXN502', '2025-01-11', 'Beauty', 'Skincare', 'Gold Renewal Cream', 40500, 17, FALSE, FALSE, 'APP', 'STANDARD');

USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW HOLIDAY_BASELINE AS
SELECT
    DIVISION,
    DEPARTMENT,
    ROUND(SUM(REVENUE) / NULLIF(SUM(QUANTITY), 0), 2) AS AVG_UNIT_PRICE,
    SUM(QUANTITY) AS TOTAL_VOLUME,
    SUM(REVENUE) AS TOTAL_REVENUE,
    COUNT(*) AS TRANSACTION_COUNT,
    ROUND(SUM(CASE WHEN IS_RETURN THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 2) AS RETURN_RATE
FROM RAW.RETAIL_TRANSACTIONS
WHERE MONTH(TRANSACTION_DATE) = 12
GROUP BY DIVISION, DEPARTMENT;

CREATE OR REPLACE VIEW POST_HOLIDAY_CURRENT AS
SELECT
    DIVISION,
    DEPARTMENT,
    ROUND(SUM(REVENUE) / NULLIF(SUM(QUANTITY), 0), 2) AS AVG_UNIT_PRICE,
    SUM(QUANTITY) AS TOTAL_VOLUME,
    SUM(REVENUE) AS TOTAL_REVENUE,
    COUNT(*) AS TRANSACTION_COUNT,
    ROUND(SUM(CASE WHEN IS_RETURN THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 2) AS RETURN_RATE
FROM RAW.RETAIL_TRANSACTIONS
WHERE MONTH(TRANSACTION_DATE) = 1
GROUP BY DIVISION, DEPARTMENT;

CREATE OR REPLACE TABLE DRIFT_DETECTION AS
SELECT
    b.DIVISION,
    b.DEPARTMENT,
    b.AVG_UNIT_PRICE AS HOLIDAY_PRICE,
    c.AVG_UNIT_PRICE AS CURRENT_PRICE,
    ROUND(((c.AVG_UNIT_PRICE - b.AVG_UNIT_PRICE) / NULLIF(b.AVG_UNIT_PRICE, 0)) * 100, 2) AS PRICE_CHANGE_PCT,
    b.TOTAL_VOLUME AS HOLIDAY_VOLUME,
    c.TOTAL_VOLUME AS CURRENT_VOLUME,
    ROUND(((c.TOTAL_VOLUME - b.TOTAL_VOLUME) / NULLIF(b.TOTAL_VOLUME, 0)) * 100, 2) AS VOLUME_CHANGE_PCT,
    b.RETURN_RATE AS HOLIDAY_RETURN_RATE,
    c.RETURN_RATE AS CURRENT_RETURN_RATE,
    CASE
        WHEN b.TRANSACTION_COUNT + c.TRANSACTION_COUNT < 4 THEN 'INSUFFICIENT_DATA'
        WHEN ABS((c.AVG_UNIT_PRICE - b.AVG_UNIT_PRICE) / NULLIF(b.AVG_UNIT_PRICE, 0)) > 0.15 THEN 'DRIFT'
        ELSE 'STABLE'
    END AS DRIFT_STATUS,
    CASE
        WHEN b.TRANSACTION_COUNT + c.TRANSACTION_COUNT >= 6 THEN 'HIGH'
        WHEN b.TRANSACTION_COUNT + c.TRANSACTION_COUNT >= 4 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS CONFIDENCE_LEVEL
FROM HOLIDAY_BASELINE b
JOIN POST_HOLIDAY_CURRENT c
    ON b.DIVISION = c.DIVISION
   AND b.DEPARTMENT = c.DEPARTMENT;

CREATE OR REPLACE VIEW DRIFT_SUMMARY AS
SELECT
    DIVISION,
    DEPARTMENT,
    HOLIDAY_PRICE,
    CURRENT_PRICE,
    PRICE_CHANGE_PCT,
    HOLIDAY_VOLUME,
    CURRENT_VOLUME,
    VOLUME_CHANGE_PCT,
    DRIFT_STATUS,
    CONFIDENCE_LEVEL,
    CASE
        WHEN DRIFT_STATUS = 'INSUFFICIENT_DATA'
            THEN 'Not enough historical purchasing activity exists to generate a reliable behavioral conclusion.'
        WHEN DRIFT_STATUS = 'DRIFT' AND PRICE_CHANGE_PCT < 0
            THEN 'Customers are shifting toward more value conscious luxury purchasing behavior after the holiday season.'
        WHEN DRIFT_STATUS = 'DRIFT' AND PRICE_CHANGE_PCT > 0
            THEN 'Customers are continuing premium purchasing behavior across luxury categories.'
        ELSE 'Customer purchasing behavior remains relatively stable.'
    END AS BUSINESS_EXPLANATION,
    CASE
        WHEN DRIFT_STATUS = 'INSUFFICIENT_DATA'
            THEN 'Monitor category activity until additional purchasing data becomes available.'
        WHEN DRIFT_STATUS = 'DRIFT' AND PRICE_CHANGE_PCT < 0
            THEN 'Consider increasing targeted promotions and expanding accessible luxury product positioning.'
        WHEN DRIFT_STATUS = 'DRIFT' AND PRICE_CHANGE_PCT > 0
            THEN 'Opportunity to strengthen premium inventory and luxury campaign positioning.'
        ELSE 'Continue current merchandising and pricing strategy.'
    END AS RECOMMENDED_ACTION
FROM DRIFT_DETECTION;

SELECT * FROM DRIFT_SUMMARY;
