-- SnowTrace fresh Snowflake setup
-- Run this in a new Snowflake worksheet after creating/signing into your account.

CREATE OR REPLACE WAREHOUSE SNOWTRACE_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE SNOWTRACE;
USE DATABASE SNOWTRACE;
USE WAREHOUSE SNOWTRACE_WH;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE RAW.RETAIL_TRANSACTIONS (
    TRANSACTION_ID INTEGER,
    TRANSACTION_DATE DATE,
    DIVISION VARCHAR,
    DEPARTMENT VARCHAR,
    UNITS_SOLD INTEGER,
    UNIT_PRICE NUMBER(10, 2),
    CHANNEL VARCHAR
);

INSERT INTO RAW.RETAIL_TRANSACTIONS
    (TRANSACTION_ID, TRANSACTION_DATE, DIVISION, DEPARTMENT, UNITS_SOLD, UNIT_PRICE, CHANNEL)
VALUES
    (1, '2025-12-03', 'Beauty', 'Skincare', 120, 3050, 'Online'),
    (2, '2025-12-18', 'Beauty', 'Skincare', 100, 3150, 'Store'),
    (3, '2026-01-08', 'Beauty', 'Skincare', 96, 3500, 'Online'),
    (4, '2026-01-24', 'Beauty', 'Skincare', 82, 3540, 'Store'),
    (5, '2025-12-08', 'Beauty', 'Makeup', 180, 2400, 'Online'),
    (6, '2026-01-12', 'Beauty', 'Makeup', 191, 2320, 'Store'),
    (7, '2025-12-05', 'Fashion', 'Handbags', 92, 18500, 'Store'),
    (8, '2026-01-15', 'Fashion', 'Handbags', 70, 21100, 'Online'),
    (9, '2025-12-16', 'Fashion', 'Footwear', 135, 9500, 'Store'),
    (10, '2026-01-17', 'Fashion', 'Footwear', 148, 9660, 'Online'),
    (11, '2025-12-10', 'Fragrance', 'Signature Scents', 160, 6200, 'Online'),
    (12, '2026-01-11', 'Fragrance', 'Signature Scents', 210, 5650, 'Store'),
    (13, '2025-12-14', 'Fragrance', 'Home Fragrance', 76, 4100, 'Store'),
    (14, '2026-01-22', 'Fragrance', 'Home Fragrance', 73, 4120, 'Online');

CREATE OR REPLACE VIEW ANALYTICS.HOLIDAY_BASELINE AS
SELECT
    DIVISION,
    DEPARTMENT,
    SUM(UNITS_SOLD) AS BASELINE_VOLUME,
    AVG(UNIT_PRICE) AS BASELINE_AVG_PRICE
FROM RAW.RETAIL_TRANSACTIONS
WHERE TRANSACTION_DATE BETWEEN '2025-12-01' AND '2025-12-31'
GROUP BY DIVISION, DEPARTMENT;

CREATE OR REPLACE VIEW ANALYTICS.POST_HOLIDAY_CURRENT AS
SELECT
    DIVISION,
    DEPARTMENT,
    SUM(UNITS_SOLD) AS CURRENT_VOLUME,
    AVG(UNIT_PRICE) AS CURRENT_AVG_PRICE
FROM RAW.RETAIL_TRANSACTIONS
WHERE TRANSACTION_DATE BETWEEN '2026-01-01' AND '2026-01-31'
GROUP BY DIVISION, DEPARTMENT;

CREATE OR REPLACE TABLE ANALYTICS.DRIFT_DETECTION AS
WITH DRIFT_BASE AS (
    SELECT
        COALESCE(B.DIVISION, C.DIVISION) AS DIVISION,
        COALESCE(B.DEPARTMENT, C.DEPARTMENT) AS DEPARTMENT,
        B.BASELINE_VOLUME,
        C.CURRENT_VOLUME,
        ROUND(B.BASELINE_AVG_PRICE, 2) AS BASELINE_AVG_PRICE,
        ROUND(C.CURRENT_AVG_PRICE, 2) AS CURRENT_AVG_PRICE,
        ROUND(((C.CURRENT_VOLUME - B.BASELINE_VOLUME) / NULLIF(B.BASELINE_VOLUME, 0)) * 100, 2) AS VOLUME_CHANGE_PCT,
        ROUND(((C.CURRENT_AVG_PRICE - B.BASELINE_AVG_PRICE) / NULLIF(B.BASELINE_AVG_PRICE, 0)) * 100, 2) AS PRICE_CHANGE_PCT
    FROM ANALYTICS.HOLIDAY_BASELINE B
    FULL OUTER JOIN ANALYTICS.POST_HOLIDAY_CURRENT C
        ON B.DIVISION = C.DIVISION
       AND B.DEPARTMENT = C.DEPARTMENT
),
SCORED AS (
    SELECT
        *,
        CASE
            WHEN BASELINE_VOLUME IS NULL OR CURRENT_VOLUME IS NULL THEN 'INSUFFICIENT_DATA'
            WHEN ABS(PRICE_CHANGE_PCT) >= 8 OR ABS(VOLUME_CHANGE_PCT) >= 18 THEN 'DRIFT'
            ELSE 'STABLE'
        END AS DRIFT_STATUS,
        CASE
            WHEN BASELINE_VOLUME IS NULL OR CURRENT_VOLUME IS NULL THEN 'Low'
            WHEN BASELINE_VOLUME + CURRENT_VOLUME >= 250 THEN 'High'
            ELSE 'Medium'
        END AS CONFIDENCE_LEVEL
    FROM DRIFT_BASE
)
SELECT
    DIVISION,
    DEPARTMENT,
    '2025-12-01'::DATE AS BASELINE_START,
    '2025-12-31'::DATE AS BASELINE_END,
    '2026-01-01'::DATE AS COMPARISON_START,
    '2026-01-31'::DATE AS COMPARISON_END,
    BASELINE_VOLUME,
    CURRENT_VOLUME,
    BASELINE_AVG_PRICE,
    CURRENT_AVG_PRICE,
    VOLUME_CHANGE_PCT,
    PRICE_CHANGE_PCT,
    DRIFT_STATUS,
    CONFIDENCE_LEVEL,
    RANK() OVER (PARTITION BY DIVISION ORDER BY ABS(PRICE_CHANGE_PCT) DESC NULLS LAST) AS DRIFT_SEVERITY_RANK,
    ROUND(AVG(PRICE_CHANGE_PCT) OVER (PARTITION BY DIVISION), 2) AS DIVISION_AVG_PRICE_CHANGE
FROM SCORED;

CREATE OR REPLACE VIEW ANALYTICS.DRIFT_SUMMARY AS
SELECT
    *,
    CASE
        WHEN BASELINE_VOLUME IS NULL OR CURRENT_VOLUME IS NULL THEN 'This department needs more complete history before a reliable read is possible.'
        WHEN DRIFT_STATUS = 'DRIFT' THEN DEPARTMENT || ' is moving differently from its holiday baseline, with a ' || PRICE_CHANGE_PCT || '% price change and ' || VOLUME_CHANGE_PCT || '% volume change.'
        ELSE DEPARTMENT || ' is broadly stable versus the selected baseline period.'
    END AS BUSINESS_EXPLANATION,
    CASE
        WHEN BASELINE_VOLUME IS NULL OR CURRENT_VOLUME IS NULL THEN 'Collect another cycle of transactions before taking action.'
        WHEN PRICE_CHANGE_PCT > 8 AND VOLUME_CHANGE_PCT < 0 THEN 'Test targeted offers or bundle mechanics before discounting the whole category.'
        WHEN PRICE_CHANGE_PCT < -8 AND VOLUME_CHANGE_PCT > 0 THEN 'Protect margin by narrowing promotions to high-intent customer segments.'
        WHEN ABS(VOLUME_CHANGE_PCT) >= 18 THEN 'Review inventory, campaign timing, and merchandising placement for this department.'
        ELSE 'Monitor the department and keep the current commercial plan.'
    END AS RECOMMENDED_ACTION
FROM ANALYTICS.DRIFT_DETECTION;

SELECT * FROM ANALYTICS.DRIFT_SUMMARY ORDER BY DIVISION, DRIFT_SEVERITY_RANK;
