-- SnowTrace fresh Snowflake setup for the Olist ecommerce dataset.
-- Run this first, then load the matching CSV files from data/raw into the RAW tables.

CREATE OR REPLACE WAREHOUSE SNOWTRACE_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE SNOWTRACE;
USE DATABASE SNOWTRACE;
USE WAREHOUSE SNOWTRACE_WH;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE RAW.ORDERS (
    ORDER_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ORDER_STATUS VARCHAR,
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP_NTZ,
    ORDER_APPROVED_AT TIMESTAMP_NTZ,
    ORDER_DELIVERED_CARRIER_DATE TIMESTAMP_NTZ,
    ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP_NTZ,
    ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE RAW.ORDER_ITEMS (
    ORDER_ID VARCHAR,
    ORDER_ITEM_ID INTEGER,
    PRODUCT_ID VARCHAR,
    SELLER_ID VARCHAR,
    SHIPPING_LIMIT_DATE TIMESTAMP_NTZ,
    PRICE NUMBER(12, 2),
    FREIGHT_VALUE NUMBER(12, 2)
);

CREATE OR REPLACE TABLE RAW.PRODUCTS (
    PRODUCT_ID VARCHAR,
    PRODUCT_CATEGORY_NAME VARCHAR,
    PRODUCT_NAME_LENGHT NUMBER,
    PRODUCT_DESCRIPTION_LENGHT NUMBER,
    PRODUCT_PHOTOS_QTY NUMBER,
    PRODUCT_WEIGHT_G NUMBER,
    PRODUCT_LENGTH_CM NUMBER,
    PRODUCT_HEIGHT_CM NUMBER,
    PRODUCT_WIDTH_CM NUMBER
);

CREATE OR REPLACE TABLE RAW.ORDER_REVIEWS (
    REVIEW_ID VARCHAR,
    ORDER_ID VARCHAR,
    REVIEW_SCORE INTEGER,
    REVIEW_COMMENT_TITLE VARCHAR,
    REVIEW_COMMENT_MESSAGE VARCHAR,
    REVIEW_CREATION_DATE TIMESTAMP_NTZ,
    REVIEW_ANSWER_TIMESTAMP TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE RAW.ORDER_PAYMENTS (
    ORDER_ID VARCHAR,
    PAYMENT_SEQUENTIAL INTEGER,
    PAYMENT_TYPE VARCHAR,
    PAYMENT_INSTALLMENTS INTEGER,
    PAYMENT_VALUE NUMBER(12, 2)
);

CREATE OR REPLACE TABLE RAW.CUSTOMERS (
    CUSTOMER_ID VARCHAR,
    CUSTOMER_UNIQUE_ID VARCHAR,
    CUSTOMER_ZIP_CODE_PREFIX INTEGER,
    CUSTOMER_CITY VARCHAR,
    CUSTOMER_STATE VARCHAR
);

CREATE OR REPLACE TABLE RAW.SELLERS (
    SELLER_ID VARCHAR,
    SELLER_ZIP_CODE_PREFIX INTEGER,
    SELLER_CITY VARCHAR,
    SELLER_STATE VARCHAR
);

CREATE OR REPLACE TABLE RAW.PRODUCT_CATEGORY_NAME_TRANSLATION (
    PRODUCT_CATEGORY_NAME VARCHAR,
    PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR
);

CREATE OR REPLACE TABLE RAW.CATEGORY_MAP (
    PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR,
    DIVISION VARCHAR
);

INSERT INTO RAW.CATEGORY_MAP VALUES
    ('health_beauty', 'Beauty & Wellness'),
    ('perfumery', 'Beauty & Wellness'),
    ('fashion_bags_accessories', 'Fashion'),
    ('fashion_shoes', 'Fashion'),
    ('fashion_male_clothing', 'Fashion'),
    ('fashion_female_clothing', 'Fashion'),
    ('fashion_underwear_beach', 'Fashion'),
    ('watches_gifts', 'Fashion'),
    ('bed_bath_table', 'Home & Living'),
    ('furniture_decor', 'Home & Living'),
    ('housewares', 'Home & Living'),
    ('home_confort', 'Home & Living'),
    ('home_comfort_2', 'Home & Living'),
    ('garden_tools', 'Home & Living'),
    ('computers_accessories', 'Electronics'),
    ('telephony', 'Electronics'),
    ('electronics', 'Electronics'),
    ('audio', 'Electronics'),
    ('small_appliances', 'Electronics'),
    ('sports_leisure', 'Lifestyle'),
    ('toys', 'Lifestyle'),
    ('books_general_interest', 'Lifestyle'),
    ('books_technical', 'Lifestyle'),
    ('stationery', 'Lifestyle'),
    ('pet_shop', 'Lifestyle');

CREATE OR REPLACE VIEW ANALYTICS.ORDER_FACT AS
SELECT
    O.ORDER_ID,
    O.CUSTOMER_ID,
    O.ORDER_STATUS,
    CAST(O.ORDER_PURCHASE_TIMESTAMP AS DATE) AS ORDER_DATE,
    COALESCE(CM.DIVISION, 'Marketplace') AS DIVISION,
    INITCAP(REPLACE(COALESCE(T.PRODUCT_CATEGORY_NAME_ENGLISH, P.PRODUCT_CATEGORY_NAME, 'uncategorized'), '_', ' ')) AS DEPARTMENT,
    OI.ORDER_ITEM_ID,
    OI.PRODUCT_ID,
    OI.SELLER_ID,
    OI.PRICE,
    OI.FREIGHT_VALUE,
    OI.PRICE + OI.FREIGHT_VALUE AS REVENUE,
    R.REVIEW_SCORE,
    DATEDIFF('day', O.ORDER_PURCHASE_TIMESTAMP, O.ORDER_DELIVERED_CUSTOMER_DATE) AS DELIVERY_DAYS
FROM RAW.ORDER_ITEMS OI
INNER JOIN RAW.ORDERS O
    ON OI.ORDER_ID = O.ORDER_ID
LEFT JOIN RAW.PRODUCTS P
    ON OI.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN RAW.PRODUCT_CATEGORY_NAME_TRANSLATION T
    ON P.PRODUCT_CATEGORY_NAME = T.PRODUCT_CATEGORY_NAME
LEFT JOIN RAW.CATEGORY_MAP CM
    ON T.PRODUCT_CATEGORY_NAME_ENGLISH = CM.PRODUCT_CATEGORY_NAME_ENGLISH
LEFT JOIN (
    SELECT ORDER_ID, AVG(REVIEW_SCORE) AS REVIEW_SCORE
    FROM RAW.ORDER_REVIEWS
    GROUP BY ORDER_ID
) R
    ON OI.ORDER_ID = R.ORDER_ID
WHERE O.ORDER_STATUS IN ('delivered', 'shipped', 'invoiced');

CREATE OR REPLACE VIEW ANALYTICS.CATEGORY_MONTHLY_METRICS AS
SELECT
    DATE_TRUNC('month', ORDER_DATE) AS ORDER_MONTH,
    DIVISION,
    DEPARTMENT,
    COUNT(*) AS UNITS_SOLD,
    ROUND(SUM(REVENUE), 2) AS REVENUE,
    ROUND(AVG(PRICE), 2) AS AVG_PRICE,
    ROUND(AVG(REVIEW_SCORE), 2) AS AVG_REVIEW_SCORE,
    ROUND(AVG(DELIVERY_DAYS), 2) AS AVG_DELIVERY_DAYS
FROM ANALYTICS.ORDER_FACT
GROUP BY ORDER_MONTH, DIVISION, DEPARTMENT;

CREATE OR REPLACE VIEW ANALYTICS.DRIFT_SUMMARY AS
WITH BASELINE AS (
    SELECT
        DIVISION,
        DEPARTMENT,
        COUNT(*) AS BASELINE_VOLUME,
        SUM(REVENUE) AS BASELINE_REVENUE,
        AVG(PRICE) AS BASELINE_AVG_PRICE,
        AVG(REVIEW_SCORE) AS BASELINE_REVIEW_SCORE,
        AVG(DELIVERY_DAYS) AS BASELINE_DELIVERY_DAYS
    FROM ANALYTICS.ORDER_FACT
    WHERE ORDER_DATE BETWEEN '2018-07-01' AND '2018-07-31'
    GROUP BY DIVISION, DEPARTMENT
),
COMPARISON AS (
    SELECT
        DIVISION,
        DEPARTMENT,
        COUNT(*) AS CURRENT_VOLUME,
        SUM(REVENUE) AS CURRENT_REVENUE,
        AVG(PRICE) AS CURRENT_AVG_PRICE,
        AVG(REVIEW_SCORE) AS CURRENT_REVIEW_SCORE,
        AVG(DELIVERY_DAYS) AS CURRENT_DELIVERY_DAYS
    FROM ANALYTICS.ORDER_FACT
    WHERE ORDER_DATE BETWEEN '2018-08-01' AND '2018-08-31'
    GROUP BY DIVISION, DEPARTMENT
),
DRIFT AS (
    SELECT
        COALESCE(B.DIVISION, C.DIVISION) AS DIVISION,
        COALESCE(B.DEPARTMENT, C.DEPARTMENT) AS DEPARTMENT,
        '2018-07-01'::DATE AS BASELINE_START,
        '2018-07-31'::DATE AS BASELINE_END,
        '2018-08-01'::DATE AS COMPARISON_START,
        '2018-08-31'::DATE AS COMPARISON_END,
        B.BASELINE_VOLUME,
        C.CURRENT_VOLUME,
        ROUND(B.BASELINE_AVG_PRICE, 2) AS BASELINE_AVG_PRICE,
        ROUND(C.CURRENT_AVG_PRICE, 2) AS CURRENT_AVG_PRICE,
        ROUND(B.BASELINE_REVENUE, 2) AS BASELINE_REVENUE,
        ROUND(C.CURRENT_REVENUE, 2) AS CURRENT_REVENUE,
        ROUND(((C.CURRENT_VOLUME - B.BASELINE_VOLUME) / NULLIF(B.BASELINE_VOLUME, 0)) * 100, 2) AS VOLUME_CHANGE_PCT,
        ROUND(((C.CURRENT_AVG_PRICE - B.BASELINE_AVG_PRICE) / NULLIF(B.BASELINE_AVG_PRICE, 0)) * 100, 2) AS PRICE_CHANGE_PCT,
        ROUND(((C.CURRENT_REVENUE - B.BASELINE_REVENUE) / NULLIF(B.BASELINE_REVENUE, 0)) * 100, 2) AS REVENUE_CHANGE_PCT,
        ROUND(C.CURRENT_REVIEW_SCORE - B.BASELINE_REVIEW_SCORE, 2) AS REVIEW_SCORE_CHANGE,
        ROUND(C.CURRENT_DELIVERY_DAYS - B.BASELINE_DELIVERY_DAYS, 2) AS DELIVERY_DAYS_CHANGE
    FROM BASELINE B
    FULL OUTER JOIN COMPARISON C
        ON B.DIVISION = C.DIVISION
       AND B.DEPARTMENT = C.DEPARTMENT
),
SCORED AS (
    SELECT
        *,
        CASE
            WHEN BASELINE_VOLUME IS NULL OR CURRENT_VOLUME IS NULL THEN 'INSUFFICIENT_DATA'
            WHEN ABS(PRICE_CHANGE_PCT) >= 8 OR ABS(VOLUME_CHANGE_PCT) >= 18 OR ABS(REVENUE_CHANGE_PCT) >= 20 OR ABS(REVIEW_SCORE_CHANGE) >= 0.4 THEN 'DRIFT'
            ELSE 'STABLE'
        END AS DRIFT_STATUS,
        CASE
            WHEN BASELINE_VOLUME IS NULL OR CURRENT_VOLUME IS NULL THEN 'Low'
            WHEN BASELINE_VOLUME + CURRENT_VOLUME >= 400 THEN 'High'
            WHEN BASELINE_VOLUME + CURRENT_VOLUME >= 120 THEN 'Medium'
            ELSE 'Directional'
        END AS CONFIDENCE_LEVEL
    FROM DRIFT
)
SELECT
    *,
    RANK() OVER (
        PARTITION BY DIVISION
        ORDER BY
            COALESCE(ABS(PRICE_CHANGE_PCT), 0)
            + COALESCE(ABS(VOLUME_CHANGE_PCT), 0)
            + COALESCE(ABS(REVENUE_CHANGE_PCT), 0) DESC
    ) AS DRIFT_SEVERITY_RANK,
    ROUND(AVG(PRICE_CHANGE_PCT) OVER (PARTITION BY DIVISION), 2) AS DIVISION_AVG_PRICE_CHANGE,
    CASE
        WHEN BASELINE_VOLUME IS NULL OR CURRENT_VOLUME IS NULL THEN DEPARTMENT || ' needs more complete order history before a reliable read is possible.'
        WHEN DRIFT_STATUS = 'DRIFT' THEN DEPARTMENT || ' moved materially versus the baseline, with ' || REVENUE_CHANGE_PCT || '% revenue change, ' || VOLUME_CHANGE_PCT || '% unit change, and ' || PRICE_CHANGE_PCT || '% average price movement.'
        ELSE DEPARTMENT || ' is broadly stable versus the selected baseline period.'
    END AS BUSINESS_EXPLANATION,
    CASE
        WHEN BASELINE_VOLUME IS NULL OR CURRENT_VOLUME IS NULL THEN 'Collect another cycle of orders before changing the commercial plan.'
        WHEN REVENUE_CHANGE_PCT < -20 AND VOLUME_CHANGE_PCT < -18 THEN 'Review demand generation, availability, and merchandising placement before discounting.'
        WHEN PRICE_CHANGE_PCT > 8 AND VOLUME_CHANGE_PCT < 0 THEN 'Test targeted offers or bundles for high-intent customers instead of broad markdowns.'
        WHEN REVIEW_SCORE_CHANGE < -0.4 THEN 'Check product quality signals and delivery experience before scaling promotions.'
        WHEN DELIVERY_DAYS_CHANGE > 2 THEN 'Investigate fulfillment delays that may be suppressing repeat demand.'
        ELSE 'Monitor the department and keep the current commercial plan.'
    END AS RECOMMENDED_ACTION
FROM SCORED;

SELECT * FROM ANALYTICS.DRIFT_SUMMARY ORDER BY DIVISION, DRIFT_SEVERITY_RANK;
